### PR TITLE
feat(elm): Add elm queries

### PR DESCRIPTION
**Pull request by nunntom**
Adds queries for [elm](https://elm-lang.org/).

### CODE REVIEW

**Comment by HiPhish** [comment]
Thanks a lot, but this PR is going to be obsolete soon because we have changed how queries are written in #43. Porting is straight-forward, I should be able to do it myself once the other PR is merged.

**Comment by HiPhish** [comment]
I have rebased on the current `master` and ported all patterns except for `union_pattern`. The issue is that the `@container` node needs to contain the two `@delimiter` nodes, or else the colours won't be assigned properly. I don't know Elm, so I don't know how to solve this.

**Comment by HiPhish** [comment]
Never mind, I think I have fixed `union_pattern` by wrapping it inside a `_` node which is the container of the whole pattern. Let me know if this is correct.

**Comment by nunntom** [comment]
Hi. Thanks Union pattern seems to be working fine but type_expression is now not highlighting.

I think it's a similar issue. The delimiters are not inside the container and type_ref isn't working as a container.

image

**Comment by nunntom** [comment]
It's working now by wrapping `type_expression` inside `_` as well.

**Comment by HiPhish** [comment]
Looks good to me. Can you please squash all the commits into one? I will merge the PR then.

**Comment by nunntom** [comment]
Done. Thanks!

**Comment by HiPhish** [comment]
Merged, thank you.

**Pull request merged**
